services:
  frontend:
    platform: linux/amd64
    build:
      context: .
      target: frontend-builder
    container_name: webrunit-frontend
    volumes:
      - ./webrunit/frontend:/app/frontend
    environment:
      PORT: 8000
      DEBUG: 1
      WATCHFILES_FORCE_POLLING: true
    ports:
      - '8000:8000'
    restart: "on-failure"
