
trigger:
  github_webhook:
    - name: "GitHub webhook"
      mq: "0mq-trigger-ghwh"

mq:
  zeromq:
    - name: "0mq-trigger-ghwh"
      queue: "0mq-trigger-ghwh"
      socket_type: "pushpull"
      url: "tcp://127.0.0.1:5680"

db:
  sqlite3:
    - name: "sqlite"

engine:
  local:
    - name: "local"

job:
  jobber:
    - name: "Terraform plan-approve-apply pipeline"

      engine:
        local:
          - name: "local"

      trigger:
        github_webhook:
          - name: "github_webhook"
            repo:
              name: "testing"
              owner:
                name: "octokitty"

      params:
        - name: "account"
          description: "The account to deploy Terraform in"
          type: "string"
          default: "project1"
        - name: "environment"
          description: "The environment to deploy Terraform in"
          type: "string"
          default: "nonprod"

      actions:
        run:
          - name: "Terraform plan"

