#!/usr/bin/env sh
set -x

if command -v apk 2>/dev/null 1>&2 ; then
    . ./pyenvrc.alpine
fi

_download_pyenv_installer

export PYENV_ROOT="$HOME/.pyenv"

_install_pyenv_build_dependencies
_run_pyenv_installer

[ -d "$PYENV_ROOT/bin" ] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Restart your shell for the changes to take effect.

# Load pyenv-virtualenv automatically by adding
# the following to ~/.bashrc:

eval "$(pyenv virtualenv-init -)"

pyenv install --skip-existing -v 3.9.17
pip install --upgrade pip

_uninstall_pyenv_build_dependencies

set +x
