#!/usr/bin/env sh

if command -v apk 2>/dev/null 1>&2 ; then
    . ./pyenvrc.alpine
fi

_download_pyenv_installer

export PYENV_ROOT="$HOME/.pyenv"

_install_pyenv_build_dependencies
_run_pyenv_installer

[ -d "$PYENV_ROOT/bin" ] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Restart your shell for the changes to take effect.

# Load pyenv-virtualenv automatically by adding
# the following to ~/.bashrc:

eval "$(pyenv virtualenv-init -)"

if [ -r ../../.python-version ] ; then
    PYENV_INSTALL_VERSION="$(cat ../../.python-version)"
fi
if [ -n "${PYENV_INSTALL_VERSION:-}" ] ; then
    CFLAGS="-fPIC -DTHREAD_STACK_SIZE=0x100000" pyenv install --skip-existing -v "${PYENV_INSTALL_VERSION}"
    pyenv global "$(pyenv versions --bare)"
    #pip install --upgrade pip
else
    echo "$0: Error: could not detect PYENV_INSTALL_VERSION; not loading pyenv"
fi

_uninstall_pyenv_build_dependencies
